### ISSUE TITLE
Biomass estimates are too high

### ISSUE THREAD

**Issue by anders-kolstad** [MadingleyR/MadingleyR#1]
Hi. 

I have noticed what seems to be an error in the biomass estimates of the cohors/functional groups/trophic levels.

I have been [testing out the model](https://anders-kolstad.github.io/MadFates_Madingley/trophic-pyramids.html) for a 4x4 degree (16 grid cell) area in Norway. The model (after just a short spin up) produces an estimate for plant biomass that is 10^15.17 kg, or 1479 Gt.
[Hoeks et al 2020](https://onlinelibrary.wiley.com/doi/full/10.1111/geb.13354) get similar estimates. This number is about 50% greater than the estimated [total biomass of the planet](https://en.wikipedia.org/wiki/Biomass_(ecology)). [Harfoot et al 2014](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001841) present a much smaller estimate of about 0.0003 Gt.

See the first link for more detailed information and testing. Hoeks et al seems to get the biomass estimate from summing the monthly values (a monthly accumulated sum). But even if we use just the biomass from a single month, and we assume there's been a g and kg mixip, we still don't get even close the Harfoots et al 2014 estimate.

This could still very well be a mistake from my end, but I'd appreciate any help invetsigating this issue.
All the best,
Anders Kolstad

**Comment by anders-kolstad** [comment]
@SHoeks

**Comment by SHoeks** [comment]
Dear Anders Kolstad,

Thanks for your concern, this is indeed something that we have to figure out. I've tried my best to wrap my head around it, please let me what you think.

First of some mistakes in the code which are now corrected (fixed in the latest code): 
- There was indeed a mix up between g and kg for the plotting part of the vegetation 
- Also the trophic pyramid calculate yearly sums (over 12 months) instead of yearly average

Reinstalling the package to version 1.0.3 will apply to above mentioned fixes.

I agree that values are higher compared to Harfoot et al. 2014. However, I think we are comparing different things. All values in paper by Harfoot are presented as biomass density (i.e. kg/km2). Here we have the absolute biomass values only. See my code below:


```R
library(MadingleyR)

# your spatial window of Norway
spatial_window <- c(5, 12, 58, 65)
plot_spatialwindow(spatial_window)

# init and run model
mdata <- madingley_init(spatial_window = spatial_window, max_cohort = 100)
mdata2 <- madingley_run(out_dir = "/Users/osx/Desktop/madtemp", madingley_data = mdata, years = 10, max_cohort = 100)

# check outputs
plot_timelines(mdata2) # with the g to kg fixes these are between 10^11 to 10^12 kg for the veg
plot_trophicpyramid(mdata2) # roughly 10^11 kg for the vegetation

# load grid properties, the list_output_paths() can be used to see all outputs by the model
gridProps <- read.csv(list_output_paths(mdata2)$grid_properties[1])

# calculate area of simulation, exclude marine grid cells
AreaKm2 <- sum(gridProps$GetCellArea[gridProps$IsMarine==0])

# get the mass, last year mean
VegMeanMass <- mean(mdata2$time_line_stocks$TotalStockBiomass[mdata2$time_line_stocks$Year==10])

# calculate log10(biomass kg / km2)
log10(VegMeanMass/AreaKm2)
```

These values are closer to Harfoot. He has roughly 10^7 in seasonal environments (see Figure 2 from his paper), we have 10^6 here maybe because its high latitude compared to overall seasonal environments. I'm still thinking about the comparison with the wiki link you added. 

Kind regards, Selwyn Hoeks

**Comment by anders-kolstad** [comment]
Thank you @SHoeks for looking into this. With these three things adressed (g vs kg; biomass density vs total biomass; monthly avg vs mountly sum) the numbers obviously change considerably, and are getting closer to what Harfoot reported on. I plan to work more on my Norwegian example in March. Perhaps I could try and find som vegetation biomass estimates from other sources (eg he national forest inventory) just to compare with. 

All the best.
Anders
